apiVersion: v1
kind: Service
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs }}
  {{- end }}
  ports:
    - name: http-geoserver
      port: 80
      protocol: TCP
      targetPort: http-geoserver
  selector:
    app: {{ template "geoserver.fullname" . }}
    release: {{ .Release.Name | quote }}
