image:
  registry: docker.io
  repository: nextcloud
  tag: 21.0.2-fpm-alpine

global:
  nextcloudAdminUser: nextcloud-admin
  nextcloudAdminPassword:
    value: 11u883n-mnas

nextcloud:
  host: nextcloud.test

postgis:
  enabled: false

redis:
  enabled: false
  auth:
    password: RfVb94Ka5x

nginx:
  enabled: false

cronjob:
  enabled: false

ingress:
  enabled: false

persistence:
  enabled: false